### ISSUE TITLE
Don't expect specifc column order in parseExport.js

### ISSUE THREAD

**Issue by andre-st** [PaulKlinger/Bookstats#1]
Hi Paul, 
I saw that your CSV parsing code expects values at specific positions although it shouldn't matter for CSV-files with a header. Your current CSV parsing will fail if Goodreads adds or removes columns. It fails with CSV-files which were created by members who didn't adhere to a specific columns order.

```javascript
...
columns[column_names.indexOf("My Rating")] === "0" ? null : parseFloat(columns[7]), // user_rating
columns[column_names.indexOf("Average Rating")] === "0" ? null : parseFloat(columns[8]), // average_rating
columns[column_names.indexOf("Number of Pages")] === "" ? null : parseFloat(columns[11]), // num_pages
...
```

Nice project so far. I <a href="https://www.goodreads.com/topic/show/19691062-select-lists-being-retired?page=4&ref=nav_bar_discussions_pane_discussion#comment_188846552">just mentioned</a> it in the Goodreads forum as GR has removed the "Most Read Authors" statistics from the website and members are looking for alternatives now.

**Comment by PaulKlinger** [comment]
Thanks, that was pretty stupid considering I'm checking the column index in the same line... 
Fixed in 706406fce8a0952f0971788519fe1789679af763

And thanks for posting about the site!
